apiVersion: apps/v1
kind: Deployment
metadata:
  name: easypay-api
  namespace: easypay
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: easypay-api
          image: noufionline/easypay-api:2.0
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: ConnectionStrings__EasyPayContext
              value: Host=easypay-backend-service;Database=$(POSTGRES_DB);Username=$(POSTGRES_USER);Password=$(POSTGRES_PASSWORD)
            - name: ASPNETCORE_URLS
              value: http://+:8080
            # - name: ASPNETCORE_URLS
            #   value: http://+:8080;https://+:8443
            # - name: ASPNETCORE_Kestrel__Certificates__Default__Path
            #   value: /https/aspnetapp.pfx
            # - name: ASPNETCORE_Kestrel__Certificates__Default__Password
            #   value: /https/aspnetapp.pfx
          resources:
            limits:
              cpu: "500m"
            requests:
              cpu: "200m"
