apiVersion: v1
kind: Service
metadata:
  name: easypay-api-service
  namespace: easypay
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - name: "http"
      protocol: TCP
      port: 80
      targetPort: 8080 
    