---
- hosts: all
  remote_user: ubuntu 
  become: yes
  vars:
    new_user: easypayadm
  tasks:
    - name: creating group {{ new_user }}
      group:
        name: "{{ new_user }}"
        state: present

    - name: creating the user {{ new_user }}.
      user:
        name: "{{ new_user }}"
        group: "{{ new_user }}"
        createhome: yes
        shell: /bin/bash
        append: yes
        password: "{{ 'easypayadm' | password_hash('sha512') }}"
        state: present
        groups: "{{new_user}},sudo"  

    - name: Create a dedicated sudo entry file for the user.
      file:
        path: "/etc/sudoers.d/{{ new_user }}"
        state: touch
        mode: '0600'

    - name: "Setting up Sudo without Password for user {{ new_user }}."
      lineinfile:
        dest: "/etc/sudoers.d/{{ new_user }}"
        line: '{{ new_user }}  ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Set authorized key for user copying it from current {{ new_user }}  user.
      authorized_key:
         user: "{{ new_user }}"
         state: present
         key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

    - name: Print the created user.
      shell: id "{{ new_user }}"
      register: new_user_created
    
    - name: Add master and worker nodes to host file
      blockinfile:
        path: /etc/hosts
        block: |
          {{ item.ip }} {{ item.name }}
        marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
      loop:
        - {name: k8s-master1, ip: 172.16.16.101 }
        - {name: k8s-worker1, ip: 172.16.16.201 }
        - {name: k8s-worker2, ip: 172.16.16.202 }
        - {name: k8s-worker3, ip: 172.16.16.202 }

    - debug:
        msg: "{{ new_user_created.stdout_lines[0] }}"
...
