---
- hosts: master
  remote_user: easypayadm
  become: yes
  gather_facts: yes
  
  tasks:
    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Pull default hello-world Docker image
      community.docker.docker_image:
        name: "hello-world"
        source: pull

    - name: Create default hello-world container
      community.docker.docker_container:
        name: "hello-world"
        image: "hello-world"
        state: present
      