apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: easypay-user-role-binding
  namespace: easypay
subjects:
- kind: User
  name: easypay-user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: easypay-role
  apiGroup: rbac.authorization.k8s.io
