apiVersion: v1
kind: PersistentVolume
metadata:
  name: easypay-postgres-pv
  namespace: easypay
  labels:
    type: local
    app: backend
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"

